import type { HousingSituation, Inputs } from '@/engine/types/inputs'
import type { PurchasePlan } from '@/engine/types/plan'
import { BUILT_IN_PRODUCTS, isBuiltInProduct } from './depositCatalogue'
import {
  BUILT_IN_LOAN_PRODUCTS,
  OTBASY_PARAM_DEFAULTS,
  isBuiltInLoanProduct,
} from './loanCatalogue'

// Bump when the Inputs shape changes — a stored blob from an older shape would
// otherwise deserialize into a half-populated object and silently skew results.
//
// Exported so the specs cannot drift from it: they used to hard-code the key as a
// string, and two of them went on passing for the wrong reason after a bump.
export const STORAGE_KEY = 'mortgage:inputs:v16'
// v16: plans gained a `term` decision (max | shortest); the four built-in plans
// were removed, so `shown` no longer references their ids.
// v15: Halyk split into two built-in loan products (halyk, halyk-fee) instead
// of one with a rate baked in.

// The deposit a plan falls back to when its own choice no longer resolves, and the
// one a freshly added plan starts on. Also what the built-in plans name in the YAML.
export const DEFAULT_SAVINGS_PRODUCT_ID = 'kaspi-deposit'

// The situation and sale month a custom plan falls back to when a saved value is
// missing or invalid — the same starting point a freshly added plan gets.
const DEFAULT_PLAN_SITUATION: HousingSituation = 'selling'
export const DEFAULT_PLAN_SALE_MONTH = 3

// Real starting position as of 2026-07. See MODEL.md for provenance of every number.
export const DEFAULT_INPUTS: Inputs = {
  start: { year: 2026, month: 7 },
  horizonMonths: 60,
  apartment: {
    price: 45_000_000,
    annualGrowthRate: 0.05,
  },
  // The flat you own today and sell to help fund the purchase — a start condition,
  // shared by every plan. Its price appreciates at the apartment growth rate up to
  // the month each plan sells it. Only 'selling' plans draw on it; turning owned
  // off disables them.
  existingApartment: {
    owned: true,
    price: 35_000_000,
  },
  cashflow: {
    // 1 000 000 earned, half of it toward housing → 500 000 free cash. Salary and
    // share are entered separately; freeCashAt multiplies them.
    monthlySalary: 1_000_000,
    mortgageShare: 0.5,
    monthlyRent: 400_000,
    // 0 by default: an unindexed income is the pessimistic, known case. Anything
    // else would be me guessing your raise schedule.
    annualIndexationRate: 0,
    // June — the common civil-service / annual-review month here.
    raiseMonth: 6,
  },
  deposits: {
    // The two Kaspi accounts, 1 021 923,88 + 356 599. They used to be itemised,
    // which only ever showed where the money sits: month 0 merges everything.
    savingsBalance: 1_378_522.88,
    // Built-ins only; the user's own deposits are added on top at load time. Which
    // deposit a plan uses is now the plan's own choice (PurchasePlan.savingsProductId).
    products: [...BUILT_IN_PRODUCTS],
  },
  // Halyk is the built-in entry in the loan-product catalogue (data/loans.yml);
  // the user's own credits are added on top at load time, same as deposits. Only
  // the personal Otbasy account state below is a literal here: it is a fact about
  // this person, not the programme.
  loans: {
    products: [...BUILT_IN_LOAN_PRODUCTS],
  },
  otbasy: {
    hasDeposit: true,
    balance: 648_509.26,
    // Both left at zero because I do not know the real figures, and a plausible
    // guess here would move the CC gate without anyone noticing. Fill them in from
    // the Otbasy statement: accrued interest is what CC is actually built from.
    accruedInterest: 0,
    monthsOpen: 0,
    ...OTBASY_PARAM_DEFAULTS,
  },
  plans: {
    // Plans are all the user's own now — built by hand or generated by "build best
    // plans for me". Nothing on the board until one of those runs.
    custom: [],
    generated: [],
    shown: [],
  },
  delayedSavingMonths: null,
}

// What a first-time user (or anyone who pressed Reset) starts the onboarding
// wizard on: the programme parameters — Otbasy rates, catalogues, price-growth,
// horizon, start month — are kept from DEFAULT_INPUTS, but every *personal* start
// condition is blanked so the user enters their own situation rather than
// inheriting the developer's figures. Personal = the flat they want, the flat
// they own, their income, savings, Otbasy account, and rent.
export const BLANK_START_INPUTS: Inputs = {
  ...structuredClone(DEFAULT_INPUTS),
  apartment: { ...DEFAULT_INPUTS.apartment, price: 0 },
  existingApartment: { owned: false, price: 0 },
  cashflow: {
    ...DEFAULT_INPUTS.cashflow,
    monthlySalary: 0,
    mortgageShare: 0,
    monthlyRent: 0,
    annualIndexationRate: 0,
  },
  deposits: { ...structuredClone(DEFAULT_INPUTS.deposits), savingsBalance: 0 },
  otbasy: {
    ...DEFAULT_INPUTS.otbasy,
    hasDeposit: false,
    balance: 0,
    accruedInterest: 0,
    monthsOpen: 0,
  },
  // Nothing on the board to begin with: the onboarding wizard's final step is where
  // the user picks which plans to compare, so a first-time run starts them empty
  // rather than pre-selecting the developer's three.
  plans: { ...DEFAULT_INPUTS.plans, shown: [] },
}

export function loadInputs(): Inputs | null {
  const raw = localStorage.getItem(STORAGE_KEY)
  if (raw === null) return null
  let parsed: unknown
  try {
    parsed = JSON.parse(raw)
  } catch {
    return null
  }
  // Only a plain object can be repaired; an array or a primitive is not this shape
  // at all and there is nothing to salvage.
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) return null
  return withPlanDefaults(withCatalogue(repair(DEFAULT_INPUTS, parsed) as Inputs))
}

export function saveInputs(inputs: Inputs): void {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(withoutBuiltIns(inputs)))
}

// The built-ins belong to data/deposits.yml, not to the user's saved blob. Keeping
// a copy would mean edits to the file never reached anyone who had already used
// the app, and a deposit deleted from the file would live on in localStorage —
// silently reclassified as one of the user's own, because "built-in" is decided by
// membership in the file.
function withoutBuiltIns(inputs: Inputs): Inputs {
  return {
    ...inputs,
    deposits: {
      ...inputs.deposits,
      products: inputs.deposits.products.filter((product) => !isBuiltInProduct(product.id)),
    },
    loans: {
      ...inputs.loans,
      products: inputs.loans.products.filter((product) => !isBuiltInLoanProduct(product.id)),
    },
  }
}

// repair() takes the plan arrays wholesale (see its comment below), so a plan saved
// with a stale deposit id — one the user has since deleted — or with a
// missing/invalid situation would reach the engine broken. Fall each field back to
// its default rather than let simulateAll throw on savingsProduct() or run against a
// situation that is not one of the three. Applied to both the hand-built and the
// generated plans. Runs after withCatalogue so the deposit list it checks ids
// against is finalised.
function withPlanDefaults(inputs: Inputs): Inputs {
  const ids = new Set(inputs.deposits.products.map((product) => product.id))
  const repairPlan = <T extends PurchasePlan>(plan: T): T => ({
    ...plan,
    situation: isSituation(plan.situation) ? plan.situation : DEFAULT_PLAN_SITUATION,
    saleMonthOffset: isWholeMonth(plan.saleMonthOffset)
      ? plan.saleMonthOffset
      : DEFAULT_PLAN_SALE_MONTH,
    // Backfill term for plans saved before it existed — an old blob simply had no
    // such field; default it to the longest-term behaviour they ran under.
    term: plan.term === 'shortest' ? 'shortest' : 'max',
    savingsProductId: ids.has(plan.savingsProductId)
      ? plan.savingsProductId
      : DEFAULT_SAVINGS_PRODUCT_ID,
  })
  return {
    ...inputs,
    plans: {
      ...inputs.plans,
      custom: inputs.plans.custom.map(repairPlan),
      generated: inputs.plans.generated
        .filter((plan) => Array.isArray(plan.categories))
        .map(repairPlan),
    },
  }
}

function isSituation(value: unknown): value is HousingSituation {
  return value === 'selling' || value === 'free' || value === 'renting'
}

function isWholeMonth(value: unknown): value is number {
  return typeof value === 'number' && Number.isInteger(value) && value >= 0
}

function withCatalogue(inputs: Inputs): Inputs {
  const ownDeposits = inputs.deposits.products.filter((product) => !isBuiltInProduct(product.id))
  const products = [...BUILT_IN_PRODUCTS, ...ownDeposits]
  const ownLoans = inputs.loans.products.filter((product) => !isBuiltInLoanProduct(product.id))
  return {
    ...inputs,
    deposits: {
      ...inputs.deposits,
      products,
    },
    loans: {
      ...inputs.loans,
      products: [...BUILT_IN_LOAN_PRODUCTS, ...ownLoans],
    },
  }
}

// Rebuild the stored blob against the defaults as a schema: take each field from
// storage when it is present and the right kind, fall back to the default when it
// is missing or wrong. A single unparseable field (a cleared input leaves "")
// then costs only that field, not the whole saved state — the failure this whole
// function exists to prevent.
//
// Arrays (the deposit catalogue) are taken wholesale; withCatalogue then reconciles
// the built-ins. STORAGE_KEY is still bumped for real shape changes.
function repair(defaults: unknown, stored: unknown): unknown {
  if (typeof defaults === 'number') {
    return typeof stored === 'number' && Number.isFinite(stored) ? stored : defaults
  }
  if (typeof defaults === 'boolean') return typeof stored === 'boolean' ? stored : defaults
  if (typeof defaults === 'string') return typeof stored === 'string' ? stored : defaults
  // A null default marks a nullable number (delayedSavingMonths): keep a real
  // number, otherwise null.
  if (defaults === null) {
    return typeof stored === 'number' && Number.isFinite(stored) ? stored : null
  }
  if (Array.isArray(defaults)) return Array.isArray(stored) ? stored : defaults
  if (typeof defaults === 'object') {
    if (typeof stored !== 'object' || stored === null || Array.isArray(stored)) return defaults
    const source = stored as Record<string, unknown>
    const out: Record<string, unknown> = {}
    for (const [key, value] of Object.entries(defaults)) {
      out[key] = repair(value, source[key])
    }
    return out
  }
  return defaults
}
